# -*- coding: utf-8 -*-
"""API firestore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Mdyp3k0gbILr_zG1AGyfD0r4TKrPQiP
"""

import firebase_admin
from flask import Flask, make_response
from flask import json, request
from firebase_admin import credentials, firestore
import datetime

cred = credentials.Certificate("blackbird-545eb-firebase-adminsdk-mbj63-6dffc14bc3.json")
firebase_admin.initialize_app(cred)



db = firestore.client()
exercise_plans = db.collection('food_plan').document('gain_weight')

update=(exercise_plans.collection('gluten_free').document('breakfast'))
update

data = {
    u'legs': {
        u'ExerciseName': ["Bodyweight Squat","Step-up", "Side-hop","BodyWeight-Calf Raise"],
        u'ExerciseID': ["L01","L02","L03","L04"],
        u'StartingWeight': ["NA","NA","NA","NA"],
        u'StartingReps': [4,4,4,4],
        u'StartingSets': [4,4,4,4],
        u'RepRange': ["4,10","4,10","4,10","4,10"],
        u'Rest': [1,1,1,1],
        u'WeightIncrement ':["NA","NA","NA","NA"],
        u'EquipmentNeeded': ["NA","NA","NA","NA"]        
    },
    u'back': {
        u'ExerciseName': ["Glute Bridge","Cat-Cow"],
        u'ExerciseID': ["B01","B02"],
        u'StartingWeight': ["NA","NA"],
        u'StartingReps': [5,5],
        u'StartingSets': [3,3],
        u'RepRange': ["4,10","4,10"],
        u'Rest': [1,1],
        u'WeightIncrement ':["NA","NA"],
        u'EquipmentNeeded': ["NA","NA"]        
    },
    u'shoulders/arms': {
        u'ExerciseName': ["Seated-Curls","Seated Shoulder Press"],
        u'ExerciseID': ["A01","A02"],
        u'StartingWeight': ["1","2"],
        u'StartingReps': [5,5],
        u'StartingSets': [3,4],
        u'RepRange': ["4,10","4,10"],
        u'Rest': [1,1],
        u'WeightIncrement ':["1","2"],
        u'EquipmentNeeded': ["Dumbbells","Shoulders Press Machine"]        
    },
    u'chest': {
        u'ExerciseName': ["Seated Chest Fly","Seated Chest Press","Kneeling Pushups"],
        u'ExerciseID': ["CH01","CH02","CH03"],
        u'StartingWeight': ["2","1","NA"],
        u'StartingReps': [5,5,4],
        u'StartingSets': [4,4,4],
        u'RepRange': ["4,10","4,10"],
        u'Rest': [1.5,1],
        u'WeightIncrement ':["2","1","NA"],
        u'EquipmentNeeded': ["Chest Fly Machine","Dumbbells","NA"]        
    },
    u'core': {
        u'ExerciseName': ["Crunch","Lying Leg-Raises"],
        u'ExerciseID': ["CR01","CR02"],
        u'StartingWeight': ["NA","NA"],
        u'StartingReps': [5,4],
        u'StartingSets': [4,4],
        u'RepRange': ["4,10","4,10"],
        u'Rest': [1,1],
        u'WeightIncrement ':["NA","NA"],
        u'EquipmentNeeded': ["NA","NA"]        
    },
}


db.collection('exercise_plan').document('level1').set(data)

data = {
    u'legs': {
        u'ExerciseName': ["Leg Press","Leg Extension", "Hamstring Curls","Goblet Squat","Calf Raises"],
        u'ExerciseID': ["L05","L06","L07","L08","L09"],
        u'StartingWeight': ["5","5","5","5","2"],
        u'StartingReps': [5,5,5,5,5],
        u'StartingSets': [4,4,4,4,4],
        u'RepRange': ["4,8","4,8","4,8","4,8"],
        u'Rest': [1.5,1.5,1.5,1.5],
        u'WeightIncrement ':["5","5","5","2.5","1"],
        u'EquipmentNeeded': ["Leg Press Machine","Leg Extension Machine","Leg Extension Machine","Kettlebell OR Dumbbells","Dumbbells"]        
    },
    u'back': {
        u'ExerciseName': ["Dumbbell Row","Seated Cable Row"],
        u'ExerciseID': ["B03","B04"],
        u'StartingWeight': ["3","5"],
        u'StartingReps': [5,5],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","4,8"],
        u'Rest': [1.5,1.5],
        u'WeightIncrement ':["1","1"],
        u'EquipmentNeeded': ["Dumbbells, Bench","Cable Machine"]        
    },
    u'shoulders/arms': {
        u'ExerciseName': ["Dumbbell Front Raise","Dumbbell Side Raise","Curls","Tricep Extension"],
        u'ExerciseID': ["A03","A04","A05","A06"],
        u'StartingWeight': ["2","2","4","2"],
        u'StartingReps': [5,5,5,5],
        u'StartingSets': [4,4,4,4],
        u'RepRange': ["4-8","4-8","4-8","4-8"],
        u'Rest': [1.5,1.5,1,1],
        u'WeightIncrement ':["1","1","1","1"],
        u'EquipmentNeeded': ["Dumbbells","Dumbbells","Dumbbells","Dumbbells"]        
    },
    u'chest': {
        u'ExerciseName': ["Dumbbell Flys","Cable Flys"],
        u'ExerciseID': ["CH04","CH05"],
        u'StartingWeight': ["2","2"],
        u'StartingReps': [5,5],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","4,8"],
        u'Rest': [1.5,1.5],
        u'WeightIncrement ':["1","2"],
        u'EquipmentNeeded': ["Dumbbells, Bench","Cable Machine"]        
    },
    u'core': {
        u'ExerciseName': ["Plank Pushups","Mountain Climbers","Weighted Cable Crunch"],
        u'ExerciseID': ["CR03","CR04","CR05"],
        u'StartingWeight': ["NA","NA","5"],
        u'StartingReps': [5,5,5],
        u'StartingSets': [4,4,4],
        u'RepRange': ["4","4","4,8"],
        u'Rest': [1,1,1],
        u'WeightIncrement ':["NA","NA","1"],
        u'EquipmentNeeded': ["NA","NA","Cable Machine"]        
    }
}


db.collection('exercise_plan').document('level2').set(data)

data = {
    u'legs': {
        u'ExerciseName': ["Barbell Squat","Split Squat"],
        u'ExerciseID': ["L10","L11"],
        u'StartingWeight': ["20","5x2"],
        u'StartingReps': [5,6],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","4,8"],
        u'Rest': [2,2.5],
        u'WeightIncrement ':["5","1x2"],
        u'EquipmentNeeded': ["Barbell, Rack","Dumbbells, Bench"]        
    },
    u'back': {
        u'ExerciseName': ["Pullups","Deadlift"],
        u'ExerciseID': ["B05","B06"],
        u'StartingWeight': ["0","20"],
        u'StartingReps': [1,3],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","4,8"],
        u'Rest': [2.5,2.5],
        u'WeightIncrement ':["2","2.5"],
        u'EquipmentNeeded': ["Pullup Bar","Barbell"]        
    },
    u'shoulders/arms': {
        u'ExerciseName': ["Skull-crushers","Military Press"],
        u'ExerciseID': ["A07","A08"],
        u'StartingWeight': ["5","20"],
        u'StartingReps': [4,4],
        u'StartingSets': [4,4],
        u'RepRange': ["4-8","4-8","4-8","4-8"],
        u'Rest': [2,2],
        u'WeightIncrement ':["1","2.5"],
        u'EquipmentNeeded': ["Dumbbells, Bench","Barbell, Rack"]        
    },
    u'chest': {
        u'ExerciseName': ["Bench Press","Dips"],
        u'ExerciseID': ["CH06","CH07"],
        u'StartingWeight': ["20","0"],
        u'StartingReps': [4,3],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","1,10"],
        u'Rest': [2.5,2.5],
        u'WeightIncrement ':["2.5","2"],
        u'EquipmentNeeded': ["Bench, Barbell, Rack","Dip Bars"]        
    },
    u'core': {
        u'ExerciseName': ["Thread-the-Needle Plank","Hollow-body Holds"],
        u'ExerciseID': ["CR06","CR07"],
        u'StartingWeight': ["NA","10"],
        u'StartingReps': [4,4],
        u'StartingSets': [4,4],
        u'RepRange': ["4,8","10"],
        u'Rest': [1,1.5],
        u'WeightIncrement ':["NA","2"],
        u'EquipmentNeeded': ["NA","NA"]        
    }
}


db.collection('exercise_plan').document('level3').set(data)

